name: conecta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  firebase_auth: ^2.0.0
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.3
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^9.5.2
  cloud_firestore: ^1.0.3
  shared_preferences: ^2.0.13
  google_sign_in: ^5.0.3
  image_picker: ^0.8.1
  file_picker: ^4.0.1
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  jitsi_meet: ^4.0.0
  # share_plus: ^4.0.3
  flutter_share_me: ^0.11.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/img/
    - assets/svg/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaDemo-Light.otf
        - asset: assets/fonts/NexaDemo-Bold.otf
